# Find Allegro 5

if(ALLEGRO5IMAGE_INCLUDE_DIR)
    # Already in cache, be silent
    set(ALLEGRO5IMAGE_FIND_QUIETLY TRUE)
endif(ALLEGRO5IMAGE_INCLUDE_DIR)

include(FindPkgConfig)

pkg_search_module(ALLEGRO5IMAGE allegro_image-${ALLEGRO5_VERSION} allegro_image-debug-${ALLEGRO5_VERSION})

mark_as_advanced(ALLEGRO5IMAGE_CFLAGS ALLEGRO5IMAGE_LDFLAGS ALLEGRO5IMAGE_LIBRARIES ALLEGRO5IMAGE_INCLUDE_DIRS)

