# Find Allegro 5

if(ALLEGRO5AUDIOCODEC_INCLUDE_DIR)
    # Already in cache, be silent
    set(ALLEGRO5AUDIOCODEC_FIND_QUIETLY TRUE)
endif(ALLEGRO5AUDIOCODEC_INCLUDE_DIR)

include(FindPkgConfig)

pkg_search_module(ALLEGRO5AUDIOCODEC allegro_acodec-${ALLEGRO5_VERSION} allegro_acodec-debug-${ALLEGRO5_VERSION})

mark_as_advanced(ALLEGRO5AUDIOCODEC_CFLAGS ALLEGRO5AUDIOCODEC_LDFLAGS ALLEGRO5AUDIOCODEC_LIBRARIES ALLEGRO5AUDIOCODEC_INCLUDE_DIRS)

