# Find Allegro 5

if(ALLEGRO5TTF_INCLUDE_DIR)
    # Already in cache, be silent
    set(ALLEGRO5TTF_FIND_QUIETLY TRUE)
endif(ALLEGRO5TTF_INCLUDE_DIR)

include(FindPkgConfig)

pkg_search_module(ALLEGRO5TTF allegro_ttf-${ALLEGRO5_VERSION} allegro_ttf-debug-${ALLEGRO5_VERSION})

mark_as_advanced(ALLEGRO5TTF_CFLAGS ALLEGRO5TTF_LDFLAGS ALLEGRO5TTF_LIBRARIES ALLEGRO5TTF_INCLUDE_DIRS)

