# Find Allegro 5

if(ALLEGRO5PRIMITIVES_INCLUDE_DIR)
    # Already in cache, be silent
    set(ALLEGRO5PRIMITIVES_FIND_QUIETLY TRUE)
endif(ALLEGRO5PRIMITIVES_INCLUDE_DIR)

include(FindPkgConfig)

pkg_search_module(ALLEGRO5PRIMITIVES allegro_primitives-${ALLEGRO5_VERSION} allegro_primitives-debug-${ALLEGRO5_VERSION})

mark_as_advanced(ALLEGRO5PRIMITIVES_CFLAGS ALLEGRO5PRIMITIVES_LDFLAGS ALLEGRO5PRIMITIVES_LIBRARIES ALLEGRO5PRIMITIVES_INCLUDE_DIRS)

