# Find Allegro 5

if(ALLEGRO5DIALOG_INCLUDE_DIR)
    # Already in cache, be silent
    set(ALLEGRO5DIALOG_FIND_QUIETLY TRUE)
endif(ALLEGRO5DIALOG_INCLUDE_DIR)

include(FindPkgConfig)

pkg_search_module(ALLEGRO5DIALOG allegro_dialog-${ALLEGRO5_VERSION} allegro_dialog-debug-${ALLEGRO5_VERSION})

mark_as_advanced(ALLEGRO5DIALOG_CFLAGS ALLEGRO5DIALOG_LDFLAGS ALLEGRO5DIALOG_LIBRARIES ALLEGRO5DIALOG_INCLUDE_DIRS)

